# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'AgoraSpeech2TextDemo' do
  
  use_frameworks!
  
  # Agora
  # Agora Rtc SDK 4.1.1
  pod 'AgoraRtcEngine_iOS', '4.2.6'
  # Agora RTM 1.6.0
  pod 'AgoraRtm_Special_iOS', '1.6.0.202'
  
  # Protobuf
  pod "Protobuf", "3.21.12"
  #  pod "Protobuf", "3.19.4"
  
  # Progress
  pod 'MBProgressHUD'
  
  # PromiseKit
  pod 'PromiseKit'
  pod 'PromiseKit/Alamofire'
  
  # DarkEggKit
  pod 'DarkEggKit', '1.0.1'
  pod 'DarkEggKit/AnimatedImageView'
  pod 'DarkEggKit/PopupMessage'
end

#
post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
    # Check out: https://github.com/flutter/flutter/issues/123852
    # Workaround for Xcode 14.3:
    # system('sed -i \'\' \'44s/readlink/readlink -f/\' \'Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh\'')
end
